### ISSUE TITLE
[Bug]: Missing favicon 

### ISSUE THREAD

**Issue by Meetjain1** [ChromeGaming/Spaceship-escort#111]
### Give a brief about the bug ✍️

Description

Favicon is missing 

### What is the expected behavior? 🤔

Description
favicon should be there .

### Provide step by step information reproduce the bug 📄

Description
will add a favicon to it .

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@Meetjain1 Before seding PR, show me design

**Comment by Meetjain1** [comment]
> @Meetjain1 Before seding PR, show me design

Actually I added the same that is there in our repo and hence created pr directly by adding the required code , but now suggesting new have a look , 

![fav space-modified](https://github.com/ChromeGaming/Spaceship-escort/assets/133582566/f9e4e773-5db5-4876-866b-dc0fc419b82f)

**Comment by Meetjain1** [comment]
@Durgesh4993 ?

**Comment by Meetjain1** [comment]
@Durgesh4993 can I add this ?

**Comment by Meetjain1** [comment]
> > @Meetjain1 Before seding PR, show me design
> 
> Actually I added the same that is there in our repo and hence created pr directly by adding the required code , but now suggesting new have a look , @Durgesh4993
> 
> ![fav space-modified](https://private-user-images.githubusercontent.com/133582566/343738579-f9e4e773-5db5-4876-866b-dc0fc419b82f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTMwNzcsIm5iZiI6MTcyMTg5Mjc3NywicGF0aCI6Ii8xMzM1ODI1NjYvMzQzNzM4NTc5LWY5ZTRlNzczLTVkYjUtNDg3Ni04NjZiLWRjMGZjNDE5YjgyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwNzMyNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDk3NWU5NTc3ZWNlY2E0NTFkMWZjMTVmMWE1ZDBiYzM5NTRlM2EzMTk0MzY0OTQwMjYxYmFkZDkyNTQwM2I5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U1QrumUXs76rXpqbDCGP7Sw7wFtxL7rTUXXduBYFDgY)

@Durgesh4993 is this good ?

**Comment by Meetjain1** [comment]
@Durgesh4993
