### ISSUE TITLE
[Bug]: Rocket gif is too blur 

### ISSUE THREAD

**Issue by Meetjain1** [ChromeGaming/Spaceship-escort#114]
### Give a brief about the bug ✍️

Description
Rocket gif quality is too low 

### What is the expected behavior? 🤔

Description
It should be fairly shown 

### Provide step by step information reproduce the bug 📄

Description
will increase its quality 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Meetjain1** [comment]
@Durgesh4993 should I update it ?

**Comment by Soujanya2004** [comment]
Hi, I have been following your project and I would love to contribute, can you please assign me this issue.

**Comment by Meetjain1** [comment]
@Durgesh4993 assign me
