### ISSUE TITLE
[Bug]:  Start Mission Button is not working

### ISSUE THREAD

**Issue by Durgesh4993** [ChromeGaming/Spaceship-escort#115]
### Give a brief about the bug ✍️

Description

### What is the expected behavior? 🤔

Description

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Saipradyumnagoud** [comment]
@Durgesh4993 Please assign me the issue

**Comment by Saipradyumnagoud** [comment]
@Durgesh4993 The issue isnt solved i want to work on it
