### ISSUE TITLE
[Bug]: Opens multiple dialog box and UI fixes.

### ISSUE THREAD

**Issue by Harsh-KumarJha** [ChromeGaming/Spaceship-escort#13]
### Give a brief about the bug ✍️

Description
![Screenshot 2024-05-12 034956](https://github.com/GameSphere-MultiPlayer/Spaceship-escort/assets/121922047/aedaa307-6cec-4877-9f7a-50a5a1fc5e6f)

- The buttons are not interactive on hover. 

![image](https://github.com/GameSphere-MultiPlayer/Spaceship-escort/assets/121922047/281574a6-3da6-4141-81c1-40ab8f18bfc7)
- When the two buttons {setting and ? } are pressed one after other, both the dialog boxes are visible and which is not desired. 
- The pause button becomes invisible when it is pressed so color combination can be better
I would like to work on this issue under GSSoC'24.

### What is the expected behavior? 🤔

Description 
The fighters can be selected based on better UI experience for the user to see the responsiveness of the game .

The dialog boxes should close when another option is clicked or when they are re-clicked.
The pause button becomes invisible on the orange color.

### Provide step by step information reproduce the bug 📄

Description

1. Add hover animation to the cards that when it is hovered over it glows to display what starship is being selected also change the cursor hover animation to give a better interface when selecting on the page. I can create hover animations to match the theme and make it interactive for the users.  and keep the classic essence same.
2. Also can make the alert status panel wider for better visual appeal.
3. The dialog boxes should close when they are clicked again or when other option is clicked.
4. The pause button could have a better color to still make it visible for the users

Hey I am really eager to contribute to this game and make it a better experience for the player and I would love to work for this under GSSoC'24. 
Kindly assign this issue to me.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by naisargi17** [comment]
can you please assign me under GSSOC.'24 .

**Comment by VedikaKayangude** [comment]
Can you please assign me this issue under GSSoC'24

**Comment by Harsh-KumarJha** [comment]
The issue is fixed at #70
