### ISSUE TITLE
[New Feature]: creating separate files for style.css and script.js

### ISSUE THREAD

**Issue by SalehaTabassum** [ChromeGaming/Spaceship-escort#17]
### 🎮 feature Request

As we can see that the css and js code is within the index.html .It would be better to place them in separate files,which will help to make code look easy to understand and we can easily make changes I different files @Durgesh4993 Please assign this issue to me under GSSOC 2024 and add necessary labels

### Point down the features

Creating 
Style.css
Script.js

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by drashtigit** [comment]
Can you please assign me this project. I have made multiple project and I will be happy to do it.

**Comment by LAKSHYA1509** [comment]
Hi .. Code Structures are important as they would help the fellow coders to understand it well and therefore i would be really really happy to work on it 
Durgesh can you please assign this task to me

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.
