### ISSUE TITLE
[Documentation Bug]: Enhance README file

### ISSUE THREAD

**Issue by d1vyadharsh1n1** [ChromeGaming/Spaceship-escort#33]
### Describe the bug ✍️

I would like to enhance the Readme file to make it more precise.

### Provide step by step information reproduce the bug 📄

I would like to create add seperate sections for tech stack, code of conduct, screenshot of the project, project admin details and contributors details

### Select program in which you are contributing

GSSoc'24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by d1vyadharsh1n1** [comment]
@Durgesh4993 I have created a pr, please check it and let me know for any changes.

**Comment by 21atha** [comment]
Sir, I would like to work on this . Please could you assign me this issue under GSSOC'24
