### ISSUE TITLE
README.md [Bug]: 

### ISSUE THREAD

**Issue by Meetjain1** [ChromeGaming/Spaceship-escort#56]
### Give a brief about the bug ✍️

There is some bug in readme.md file , that the emoji is missing and that are present are not animated and some allignment fix needed .
@Durgesh4993 assign this issue to me I will fix it as I have done in your previous projects . Thankyou

![spaceship](https://github.com/GameSphere-MultiPlayer/Spaceship-escort/assets/133582566/b14b13c0-e888-4bd3-a22b-375ea9036bc4)

### What is the expected behavior? 🤔

Emojis should be present and animated to attract the contributors 

### Provide step by step information reproduce the bug 📄

will add the animated emojis .

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by SarthakJaindebugger** [comment]
@Meetjain1 the emoji 
![Screenshot 2024-05-26 112747](https://github.com/GameSphere-MultiPlayer/Spaceship-escort/assets/84659102/8b5bfa13-ff74-4bb2-94d3-e8583829fb8e)
(pink heart) is visible to me. Plz check once.

**Comment by Meetjain1** [comment]
> @Meetjain1 the emoji (pink heart) is visible to me. Plz check once.
> 
> ![Screenshot 2024-05-26 112747](https://private-user-images.githubusercontent.com/84659102/333850548-8b5bfa13-ff74-4bb2-94d3-e8583829fb8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDQ5NjIsIm5iZiI6MTcxNjcwNDY2MiwicGF0aCI6Ii84NDY1OTEwMi8zMzM4NTA1NDgtOGI1YmZhMTMtZmY3NC00YmIyLTk0ZDMtZTg1ODM4MjlmYjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDA2MjQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmYjRjZDkwNmMyOWI3OTk2NWE1ZjNkNjg1ZWJjMjYxNmRjYmYxOTljOGI1Y2M3ZjE2ZTc3YWY4YWE5YjkyZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1rKtjuD52f-nqXiItevicnczei9Y_j9luTQp19Jt_2g)

yes it is visible now , I can replace these static emojis with animated emojis if you want otherwise no problem .

**Comment by SarthakJaindebugger** [comment]
@Durgesh4993 what exactly u want in place of it, or is it fine ?

**Comment by Meetjain1** [comment]
let me know what to do .

**Comment by Meetjain1** [comment]
@Durgesh4993 ?

**Comment by Durgesh4993** [comment]
@Meetjain1 As your wise

**Comment by Meetjain1** [comment]
> @Meetjain1 As your wise

OK @Durgesh4993 , please assign me
