### ISSUE TITLE
[New Feature]: Adding a side navbar containing required tabs like About, Game Rules

### ISSUE THREAD

**Issue by Amruta7203** [ChromeGaming/Spaceship-escort#77]
### 🎮 feature Request

Functionality:

The navigation bar will be positioned vertically along the side of the webpage (typically left or right).
It will contain a list of clickable tabs for easy access to important information sections.

This will improve user interface and experience.

### Point down the features

Initial Tabs:

About: This tab will lead users to a dedicated page or section that provides information about the game, its concept, and background.
Game Rules: This tab will direct users to a comprehensive explanation of the game's mechanics, objectives, and winning conditions.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by KomalSrivastava** [comment]
@ChromeGaming 
*Description:
Implement a side navbar on the website that includes essential tabs such as About, Game Rules, and other relevant sections.

*Reason for Change:
Introducing a side navbar will enhance navigation, allowing users to easily access important information and sections of the website without cluttering the main content area. This will improve the overall user experience by providing a structured and organized interface.

*Current Setup:
Currently, there is no side navbar available on the website, and important tabs like About and Game Rules might be hard to locate.

*Proposed Feature:

**Add a side navbar that contains tabs for essential sections such as:

~About
~Game Rules
~Contact
~FAQs
~Any other relevant sections
~Ensure the side navbar is responsive and accessible on various devices and screen sizes.

*Screenshots or Design Mockups (optional):
 N/A

*Additional Information (optional):
The side navbar should seamlessly integrate with the existing design and color scheme of the website. It should also be easy to update and expand as new sections or information are added to the website.

*Priority Level (optional):

~Low
~Medium
~High

*Timeline (optional):
[Specify any preferred or required timeline for implementing the feature.]

*Possible Implementation Approach (optional):

~Design the side navbar with CSS to ensure it is visually appealing and consistent with the website's theme.
~Use JavaScript to handle the dynamic display of content when different tabs are clicked.
~Test the side navbar for usability and functionality across different browsers and devices.

Please add the "gssoc24" label and assign this issue to me. I'm excited to contribute to improving the project's user experience by adding a side navbar with essential tabs.
