### ISSUE TITLE
[New Feature]: create a 404 not found page

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [ChromeGaming/Spaceship-escort#79]
### 🎮 feature Request

create a 404 not found page

### Point down the features

create a 404 not found page

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by AbhinaySngh** [comment]
@Durgesh4993 Can you please assign me this issue, abhi thik kr k deta hu.
