### ISSUE TITLE
[Enhancement]: Fixing UI of home page

### ISSUE THREAD

**Issue by HarshitGupta1511** [ChromeGaming/Spaceship-escort#95]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Making text and headings much for clear with proper spacing and including better colour hover effects.

### Describe the solution you'd like

Solution steps can work on CSS of home page and make it much attractive , the text written is too over coloured . I want to add hover effects to home page to make it more attractive and clear.

please assign me this issue @Durgesh4993 
![Uploading Screenshot 2024-06-08 at 2.53.10 PM.png…]()

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Pragya1601** [comment]
please assign this issue to me

**Comment by Vibha17** [comment]
Hi I am Vibha Gupta and I would like to fix the issue.

I am working under GSSoC'24. Please assign me this issue.
